version: '3.8'

services:
  water-quality-api:
    image: derek2403/water1:latest  # New unique image name
    container_name: water-quality-api
    platform: linux/amd64
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=predict.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Increased to give more time for model loading