version: '3.8'

services:
  water-quality-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: derek2403/water-quality-api:latest
    container_name: water-quality-api
    platform: linux/amd64
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=predict.py
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s